### ISSUE TITLE
Error when using images

### ISSUE THREAD

**Issue by bartos97** [boomanaiden154/quillgethtml#1]
When you upload image in the editor exception like this:
> TypeError: element.insert.split is not a function

 is thrown from 
`element.insert.split(/(\n)/g).forEach(function(textElement)`
which is in quillgethtml.js on line 33.
This is caused becouse element.insert is object with one property `image` which contains base64 image data as string.

**Comment by boomanaiden154** [comment]
Sorry I didn't get this fixed sooner(Wasn't watching the project), but it should be fixed as of the latest commit([4699edf](https://github.com/boomanaiden154/quillgethtml/commit/4699edf96401dea4991dfa4aa48eccff6a6f1a19)). Thanks for letting me know about the issue, and for providing good debug info.
